### ISSUE TITLE
Docs disappearing!

### ISSUE THREAD

**Issue by Schwartz10** [ceramicnetwork/js-ceramic#663] opened 2020-12-15 16:57 UTC
This one is hard to replicate, but I think i can consistently reproduce in my env right now. Discord me to set up a zoom pair asap so I can show you!

Basically, I have a line of code that sets a doc on a custom IDX definition like:

```js
    await idx.set("permissions", {
      [requesterDID]: "xxyy",
    });
```

later on I have a `checker` IDX instance, which is just responsible for checking `permissions` docs, it looks something like like:

```js
      const checker = new IDX({ ceramic, aliases });
      const perms = await checker.get<Record<string, string>>(
        "permissions",
        did
      );

    // returns null
```

The `checker` will (frequently but not always) return `null` (which is obviously a show-stopping bug, since we can't find the information we need for access control).

I can validate that `did` and `idx.id` match between those two code snippets (i'm not accidentally checking the `permissions` on the wrong DID).

_However..._ (and not sure if this is a red herring // just coincidental)

When I _immediately_ `get` the `permissions` after setting it, the `checker` (later on) returns the right permission:

```js
    await idx.set("permissions", {
      [requesterDID]: "xxyy",
    });
   await idx.get("permissions", idx.id)
```
... later on somewhere else....

```js
 const checker = new IDX({ ceramic, aliases });
  const perms = await checker.get<Record<string, string>>(
        "permissions",
        did
      );

// returns the right permissions!
```

Any ideas why this might be happening?

**Comment by stbrody** [comment] 2020-12-15 17:40
When you hit this issue, does it continue to fail indefinitely for that IDX document?  Or can it go from working to failing to back to working?  Can you send logs from ceramic and IDX for us to look at from when the issue is happening?

**Comment by Schwartz10** [comment] 2020-12-18 16:27
Just an update here - this is very likely due to me forgetting to set the right pinning options in a couple places. Related to: https://github.com/ceramicnetwork/js-ceramic/issues/676 and https://github.com/ceramicnetwork/js-ceramic/issues/677

I will be testing this again today in more depth and will close if things appear to be open

**Comment by oed** [comment] 2021-02-09 12:58
Closing since this has most likely been solved .)

**Closed by oed** 2021-02-09 12:58 UTC
