### ISSUE TITLE
Implement more efficient merkle tree

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/js-ceramic#446] opened 2020-10-29 11:42 UTC

**Comment by stbrody** [comment] 2020-10-29 13:53
Dupe of https://github.com/ceramicnetwork/ceramic-anchor-service/issues/124? @oed

**Comment by stbrody** [comment] 2020-10-29 14:22
Is there a design somewhere for what this more efficient merkle tree will look like? @oed

**Comment by oed** [comment] 2020-10-29 14:29
Not yet, there should be but it's only been discussed so far. Main idea is for merkle nodes to go from being maps to being arrays.
**Now:**
```
{
  L: <CID1>,
  R: <CID2>
}
```

**After this:**
```
[<cid1>, <cid2>]
```

**Comment by simonovic86** [comment] 2020-10-29 14:37
@oed @stbrody this change directly affects checks in `js-ceramic`.

https://github.com/ceramicnetwork/js-ceramic/blob/27fed9f72b1e1dd415920a9fc3c831482e2a214f/packages/ceramic-core/src/document.ts#L507

**Comment by oed** [comment] 2020-10-29 14:57
I assume in js-ceramic we can easily support both the new and the old format?

**Comment by simonovic86** [comment] 2020-10-29 14:59
@oed yep 👍

**Comment by stbrody** [comment] 2020-12-02 21:43
There's no easy way to test that js-ceramic is resilient to the changes in the merkle tree format from https://github.com/ceramicnetwork/ceramic-anchor-service/issues/124, but from code inspection I believe it should be and there's nothing actually to do here.  I filed https://github.com/ceramicnetwork/ceramic-anchor-service/issues/199 which will get us better test coverage here.

**Closed** 2020-12-02 21:44 UTC
Labels: Protocol: Enhancement
